Pearson-Advance/openedx-external-enrollments

openedx_external_enrollments/api/urls.py
openedx_external_enrollments/apps.py
openedx_external_enrollments/edxapp_wrapper/backends/courseware_i_v1.py
openedx_external_enrollments/signal_receivers.py

This PR removes signal receivers connected to the "CourseEnrollment" model in order to only react when Enrollment changes.

Changing event to listen for external enrollments.

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
openedx_external_enrollments/settings/common.py
openedx_external_enrollments/settings/production.py

**Ticket:** PAE-536
Change the payload to the salesforce request.

Added and removed attributes from salesforce payload

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py

**Ticket**: PAE-536
I have added again the values Lead_Source, Company and Type_Hidden also, have added the new "_get_course_key" function to generate te CourseID.

Added new valid keys to the payload

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py

**Ticket**: PAE-536
Adding the option of using the first and last name from the model user.

fix the issue when try split the full name without last name

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py

**Ticket**: PAE-536
Rename utm_params to UTM_Parameters and change the default value to an empty string.

Rename utm_params to UTM_Parameters

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py

**Ticket**: PAE-536
Changed the UTM_Parameters value to an urlencode format and added a new method to decode utm_params.

Change UTM_Parameters structure and added decode utm params method

---

.gitignore
CHANGELOG.md
openedx_external_enrollments/external_enrollments/base_external_enrollment.py
openedx_external_enrollments/external_enrollments/icc_external_enrollment.py
openedx_external_enrollments/factory.py
openedx_external_enrollments/settings/common.py
openedx_external_enrollments/settings/production.py
openedx_external_enrollments/tests/external_enrollments/tests_icc_external_enrollment.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/pip-tools.txt
requirements/test.txt

This PR adds a new controller for ICC external enrollment integration requested in [PAE-538](https://pearsonadvance.atlassian.net/browse/PAE-538?atlOrigin=eyJpIjoiNmE1M2M4MTY5OTc2NGEyOTk2NjczMjE2NzBhYzEyNDciLCJwIjoiaiJ9) ticket.

Adding ICC external enrollment controller.

---

CHANGELOG.md
openedx_external_enrollments/external_enrollments/icc_external_enrollment.py

This PR solves the issue to make sure the username is in lowercase because ICC user creation API only accepts username in lowercase.

Make the username in lowercase.

---

CHANGELOG.md
openedx_external_enrollments/external_enrollments/icc_external_enrollment.py
openedx_external_enrollments/settings/common.py

This PR adds a site configuration flag to override the default ICC platform authentication.
Also remove unused code lines.

Add site configuration flag to override ICC Authentication method

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py

This PR adds capabilities to handle the case when a basket holds multiple items, and not all of them have salesforce data related.
Context can be found [here](https://pearsonadvance.atlassian.net/browse/PAE-650).

PAE-650 Iterating through all courses in the basket to get salesforce data.

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
openedx_external_enrollments/models.py

This PR fix a SalesForseEnrollment bug and also Other course settings module name.

Fix bug on Salesforce enrollment and Other course settings module name.

---

openedx_external_enrollments/settings/common.py

Description
---------------
Set a default value for MIT_HZ_API_URL

Add default url for MIT Horizon API

---

openedx_external_enrollments/external_enrollments/mit_hz_external_enrollment.py

Description
---------------
Fix a TypeError

PAE-628-3 - Fix MIT Horizon TypeError

---

openedx_external_enrollments/external_enrollments/mit_hz_external_enrollment.py
openedx_external_enrollments/settings/common.py
openedx_external_enrollments/settings/production.py
openedx_external_enrollments/settings/test.py
setup.cfg

Description
---------------
add settings mapping for MIT HZ in prod.

PAE-628.4 - Add settings for prod environment for MIT HZ

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py

This PR makes sure source fields will be populated from course/program configs (if available).
More context: [PAE-684](https://pearsonadvance.atlassian.net/browse/PAE-684)

Removing the relation between UTM paramas and source fields.

---

openedx_external_enrollments/edxapp_wrapper/backends/course_settings_j_v1.py

Change condition to migrate and update courses in OtherCourseSettings table.
This will allow those courses that have at least  `external_platform_target`  key with value.

Change condition to migrate and update courses in OtherCourseSettings table.

---

openedx_external_enrollments/admin.py
openedx_external_enrollments/apps.py
openedx_external_enrollments/external_enrollments/viper_external_enrollment.py
openedx_external_enrollments/settings/test.py
openedx_external_enrollments/tasks.py
openedx_external_enrollments/tests/external_enrollments/tests_viper_external_enrollment.py
openedx_external_enrollments/tests/tests_factory.py
openedx_external_enrollments/tests/tests_tasks.py

This PR adds support for API refresh keys triggered by a task.

Viper API refresh keys feature triggered by a task.

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
openedx_external_enrollments/tests/external_enrollments/tests_salesforce_external_enrollment.py

This PR has the purpose to extend the SF integration to handle a new case, which consists of a program purchase type with no program metadata, therefore the SF external controller must get the data from the first course with SF metadata.
Ticket: [PAE-781](https://pearsonadvance.atlassian.net/browse/PAE-781)
does not exist and bundle type = 'special offer', then pick-up POI/IH from first course with SF metadata (expected to be the non-HZ course)

PAE-781 - Handle the interim new case

---

openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
openedx_external_enrollments/tests/external_enrollments/tests_salesforce_external_enrollment.py

This PR is intended to fix the bundle type inconsistency.  This is a patch for #40.

Change the CUSTOM_BUNDLE_TYPE value

---

openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
openedx_external_enrollments/tests/external_enrollments/tests_pathstream_external_enrollments.py

This PR is intended to add the username, fullname, first name and last name in the string that is returned by `_get_enrollment_data` and also use `EnrollmentRequestLog` to persist logging information related to the enrollment.

PAE-702.3 - Update data format and use EnrollmentRequestLog.

---

openedx_external_enrollments/api/v0/views.py

This PR allows activating the Salesforce enrollment controller using a per site criteria.
[Context](https://agile-jira.pearson.com/browse/PAE-130)

PAE-130 | Enable/disable Salesforce enrollments per site
